# IN ORDER TO CHECK THE DATATYPE USE - typeof()

In [4]:
typeof(10)

Int64

In [5]:
typeof("Hello")

String

# IN ORDER TO PRINT USE - println()

In [8]:
rank = 10
grade = 90
class_perf = rank * grade
println(class_perf)
# println includes a new line print doesnt

900


In [9]:
pi

π = 3.1415926535897...

In [10]:
100 % 3

1

In [11]:
100 ^ 3

1000000

# Multi line commenting

In [12]:
#= Hi 
this 
is my 
first Julia 
Notebook.
BYE!! =#

# Multi line string

In [13]:
s1 = """ This is first line.
This is second line.
This is third line. """

" This is first line.\nThis is second line.\nThis is third line. "

In [15]:
println(s1)

 This is first line.
This is second line.
This is third line. 


In [16]:
s1 = """ This is my father's laptop """

" This is my father's laptop "

In [17]:
println(s1)

 This is my father's laptop 


# String interpolation like string literals in Py

In [18]:
println(""" My class performance is $class_perf """)

 My class performance is 900 


In [19]:
println(""" My class performance is $(class_perf+10) """)

 My class performance is 910 


# String Concatenation

In [26]:
# ; so that it doesn't print the contents of the last variable
m1 = " I am loving"
m2 = " Julia ";


In [27]:
string(m1,m2)

" I am loving Julia "

# String Repetation

In [29]:
m1 ^ 100

" I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I 

# String Slicing

### Indexing starts from 1 in Julia

In [35]:
println(m1[1], m1[2], m1[3], m1[4], m1[5])

 I am


In [37]:
m1[2:5] # var[start index (inclusive) : end index (inclusive)]

"I am"

In [39]:
println("This is a $(typeof('m'))")

This is a string Char

In [41]:
print("This is a $(typeof("ml"))")

This is a String

# Array - Can store both homogeneous and non homogeneous data types

In [1]:
arr = [1,3,4]

3-element Array{Int64,1}:
 1
 3
 4

In [2]:
minimum(arr)

1

In [3]:
maximum(arr)

4

In [6]:
arr = [1,2,3,"boom", true]

5-element Array{Any,1}:
    1
    2
    3
     "boom"
 true

In [7]:
typeof(arr[4])

String

In [9]:
typeof(arr[5])

Bool

In [10]:
[1,2,3] + [4,5,6]

3-element Array{Int64,1}:
 5
 7
 9

In [12]:
z = zeros(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [13]:
o = ones(10)

10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [14]:
# append operation
push!(arr, "Bam!!")

6-element Array{Any,1}:
    1
    2
    3
     "boom"
 true
     "Bam!!"

In [16]:
println(arr)

Any[1, 2, 3, "boom", true, "Bam!!"]


In [17]:
sort([10,5,3])

3-element Array{Int64,1}:
  3
  5
 10

# Having an ! mark means inplace operation

# Compound data types in Julia

# Array

In [19]:
range(1, stop = 100, step = 10)

1:10:91

In [20]:
range(-10, stop = 100, length = 10)

-10.0:12.222222222222221:100.0

In [21]:
arr = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [22]:
arr1 = arr

3-element Array{Int64,1}:
 1
 2
 3

In [23]:
arr1[1]  = 10

10

In [24]:
print(arr1, arr)

[10, 2, 3][10, 2, 3]

# So this proves that no deep copy was made. The same variables has different name in the same memory location

In [25]:
arr1 = copy(arr)

3-element Array{Int64,1}:
 10
  2
  3

In [26]:
arr1[1] = 100

100

In [27]:
println(arr1, arr)

[100, 2, 3][10, 2, 3]


# Check if a particular element exits in an Array

In [28]:
in(100, arr1)

true

# Tuples

In [29]:
t1 = (1,2,3)

(1, 2, 3)

In [30]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [32]:
t1[1] = 10
# tuples are immutable as always

LoadError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Int64, ::Int64)

In [33]:
length(t1)

3

# Dictionary

In [34]:
d1 = Dict("B"=>10,"C"=>11)

Dict{String,Int64} with 2 entries:
  "B" => 10
  "C" => 11

In [36]:
keys(d1)

Base.KeySet for a Dict{String,Int64} with 2 entries. Keys:
  "B"
  "C"

In [37]:
values(d1)

Base.ValueIterator for a Dict{String,Int64} with 2 entries. Values:
  10
  11

In [38]:
d1["C"]

11

# Loop

In [43]:
for (k,v) in d1
    println("$k,$v")
end

B,10
C,11


# Convert dictionary values to array

In [47]:
a = collect(values(d1))
println(a)

[10, 11]


# Check if a key exits in a dictionary

In [48]:
in("B", collect(keys(d1)))

true

### Better method

In [50]:
haskey(d1, "C")

true