# IN ORDER TO CHECK THE DATATYPE USE - typeof()

In [4]:
typeof(10)

Int64

In [5]:
typeof("Hello")

String

# IN ORDER TO PRINT USE - println()

In [8]:
rank = 10
grade = 90
class_perf = rank * grade
println(class_perf)
# println includes a new line print doesnt

900


In [9]:
pi

π = 3.1415926535897...

In [10]:
100 % 3

1

In [11]:
100 ^ 3

1000000

# Multi line commenting

In [12]:
#= Hi 
this 
is my 
first Julia 
Notebook.
BYE!! =#

# Multi line string

In [13]:
s1 = """ This is first line.
This is second line.
This is third line. """

" This is first line.\nThis is second line.\nThis is third line. "

In [15]:
println(s1)

 This is first line.
This is second line.
This is third line. 


In [16]:
s1 = """ This is my father's laptop """

" This is my father's laptop "

In [17]:
println(s1)

 This is my father's laptop 


# String interpolation like string literals in Py

In [18]:
println(""" My class performance is $class_perf """)

 My class performance is 900 


In [19]:
println(""" My class performance is $(class_perf+10) """)

 My class performance is 910 


# String Concatenation

In [26]:
# ; so that it doesn't print the contents of the last variable
m1 = " I am loving"
m2 = " Julia ";


In [27]:
string(m1,m2)

" I am loving Julia "

# String Repetation

In [29]:
m1 ^ 100

" I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I am loving I 

# String Slicing

### Indexing starts from 1 in Julia

In [35]:
println(m1[1], m1[2], m1[3], m1[4], m1[5])

 I am


In [37]:
m1[2:5] # var[start index (inclusive) : end index (inclusive)]

"I am"

In [39]:
println("This is a $(typeof('m'))")

This is a string Char

In [41]:
print("This is a $(typeof("ml"))")

This is a String

# Array - Can store both homogeneous and non homogeneous data types

In [1]:
arr = [1,3,4]

3-element Array{Int64,1}:
 1
 3
 4

In [2]:
minimum(arr)

1

In [3]:
maximum(arr)

4

In [6]:
arr = [1,2,3,"boom", true]

5-element Array{Any,1}:
    1
    2
    3
     "boom"
 true

In [7]:
typeof(arr[4])

String

In [9]:
typeof(arr[5])

Bool

In [10]:
[1,2,3] + [4,5,6]

3-element Array{Int64,1}:
 5
 7
 9

In [12]:
z = zeros(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [13]:
o = ones(10)

10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [14]:
# append operation
push!(arr, "Bam!!")

6-element Array{Any,1}:
    1
    2
    3
     "boom"
 true
     "Bam!!"

In [16]:
println(arr)

Any[1, 2, 3, "boom", true, "Bam!!"]


In [17]:
sort([10,5,3])

3-element Array{Int64,1}:
  3
  5
 10

# Having an ! mark means inplace operation

# Compound data types in Julia

# Array

In [19]:
range(1, stop = 100, step = 10)

1:10:91

In [20]:
range(-10, stop = 100, length = 10)

-10.0:12.222222222222221:100.0

In [21]:
arr = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [22]:
arr1 = arr

3-element Array{Int64,1}:
 1
 2
 3

In [23]:
arr1[1]  = 10

10

In [24]:
print(arr1, arr)

[10, 2, 3][10, 2, 3]

# So this proves that no deep copy was made. The same variables has different name in the same memory location

In [25]:
arr1 = copy(arr)

3-element Array{Int64,1}:
 10
  2
  3

In [26]:
arr1[1] = 100

100

In [27]:
println(arr1, arr)

[100, 2, 3][10, 2, 3]


# Check if a particular element exits in an Array

In [28]:
in(100, arr1)

true

# Tuples

In [29]:
t1 = (1,2,3)

(1, 2, 3)

In [30]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [32]:
t1[1] = 10
# tuples are immutable as always

LoadError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Int64, ::Int64)

In [33]:
length(t1)

3

# Dictionary

In [34]:
d1 = Dict("B"=>10,"C"=>11)

Dict{String,Int64} with 2 entries:
  "B" => 10
  "C" => 11

In [36]:
keys(d1)

Base.KeySet for a Dict{String,Int64} with 2 entries. Keys:
  "B"
  "C"

In [37]:
values(d1)

Base.ValueIterator for a Dict{String,Int64} with 2 entries. Values:
  10
  11

In [38]:
d1["C"]

11

# Loop

In [43]:
for (k,v) in d1
    println("$k,$v")
end

B,10
C,11


# Convert dictionary values to array

In [47]:
a = collect(values(d1))
println(a)

[10, 11]


# Check if a key exits in a dictionary

In [48]:
in("B", collect(keys(d1)))

true

### Better method

In [50]:
haskey(d1, "C")

true

# Sets

In [1]:
s1 = Set([1,3,6,6])

Set{Int64} with 3 elements:
  3
  6
  1

In [2]:
s2 = Set([3,6,4,3])

Set{Int64} with 3 elements:
  4
  3
  6

In [6]:
println(union(s1,s2))

Set([4, 3, 6, 1])


In [7]:
intersect(s1,s2)

Set{Int64} with 2 elements:
  3
  6

# Decision Making 

In [11]:
N = 10
if N > 0
    println("$N is +ve")
else
    println("$N is -ve")
end

10 is +ve


In [16]:
N = 12569-1000
if N> 25
    println("$N is greater than 25")
elseif (N>0 && N <=25)
    println("$N is between 0 and 25")
else
    println("$N is negative number")
end

11569 is greater than 25


# Looping

In [23]:
for i  = 1:10, j = 2:20
    println("Value if i is $(i) and j is $(j)")
end

Value if i is 1 and j is 2
Value if i is 1 and j is 3
Value if i is 1 and j is 4
Value if i is 1 and j is 5
Value if i is 1 and j is 6
Value if i is 1 and j is 7
Value if i is 1 and j is 8
Value if i is 1 and j is 9
Value if i is 1 and j is 10
Value if i is 1 and j is 11
Value if i is 1 and j is 12
Value if i is 1 and j is 13
Value if i is 1 and j is 14
Value if i is 1 and j is 15
Value if i is 1 and j is 16
Value if i is 1 and j is 17
Value if i is 1 and j is 18
Value if i is 1 and j is 19
Value if i is 1 and j is 20
Value if i is 2 and j is 2
Value if i is 2 and j is 3
Value if i is 2 and j is 4
Value if i is 2 and j is 5
Value if i is 2 and j is 6
Value if i is 2 and j is 7
Value if i is 2 and j is 8
Value if i is 2 and j is 9
Value if i is 2 and j is 10
Value if i is 2 and j is 11
Value if i is 2 and j is 12
Value if i is 2 and j is 13
Value if i is 2 and j is 14
Value if i is 2 and j is 15
Value if i is 2 and j is 16
Value if i is 2 and j is 17
Value if i is 2 and j is 18
Value if

In [20]:
for i in collect(range(1,step = 10, stop = 50))
    println(i)
end

1
11
21
31
41


In [25]:
arr = [1,2,3,"Boom"]

4-element Array{Any,1}:
 1
 2
 3
  "Boom"

In [26]:
for i in arr
    println(i)
end

1
2
3
Boom


In [28]:
i = 1
while i < 5
    println(i)
    i = i+1
end

1
2
3
4


# Function

In [29]:
function greeting()
    println("Henlo User")
end

greeting (generic function with 1 method)

In [30]:
greeting()

Henlo User


In [31]:
function greeting(user_name)
    println("Henlo User $(user_name)")
end

greeting (generic function with 2 methods)

In [32]:
greeting("Bishwarup")

Henlo User Bishwarup


# Single line functions can be written as 

In [35]:
greeting(user_name) = println("Henlo User $(user_name)")

greeting (generic function with 2 methods)

In [36]:
greeting("Boomer")

Henlo User Boomer


# lambda function

In [38]:
greeting()  = user_name -> println("Henlo user $(user_name)")

greeting (generic function with 2 methods)

In [39]:
greeting("boimer")

Henlo User boimer


In [42]:
function add(x,y)
    z = x+y
    # no return is required as the last line will be returned automatically
end

add (generic function with 1 method)

In [43]:
add(10,100)

110

In [44]:
function add(x,y)
    z = x+y
    return z
end

add (generic function with 1 method)

In [45]:
add(10,100)

110

# Mapping a function to each element

In [48]:
function sq(ele)
    return ele^2
end

sq (generic function with 1 method)

In [50]:
map(sq, [2,3,4,5])

4-element Array{Int64,1}:
  4
  9
 16
 25

# Packages

In [51]:
using Pkg

In [52]:
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Pkg.jl:554


Dict{String,VersionNumber} with 1 entry:
  "IJulia" => v"1.21.4"

# Remove any package

In [53]:
Pkg.rm()

LoadError: rm requires at least one package

# Installing Pkg

In [54]:
Pkg.add("Statistics")

   Updating registry at `C:\Users\bishw\.julia\registries\General`
  Resolving package versions...
Updating `C:\Users\bishw\.julia\environments\v1.5\Project.toml`
  [10745b16] + Statistics
Updating `C:\Users\bishw\.julia\environments\v1.5\Manifest.toml`
  [37e2e46d] + LinearAlgebra
  [2f01184e] + SparseArrays
  [10745b16] + Statistics


In [55]:
using Statistics

In [57]:
mean([10,20,10])

13.333333333333334

# Vector & Matrix Processing

In [58]:
using Pkg
Pkg.add("Random")
using Random

  Resolving package versions...
Updating `C:\Users\bishw\.julia\environments\v1.5\Project.toml`
  [9a3f8284] + Random
No Changes to `C:\Users\bishw\.julia\environments\v1.5\Manifest.toml`


In [59]:
rand(10)

10-element Array{Float64,1}:
 0.0564848985794113
 0.5803463430162672
 0.5772809916970412
 0.6706997989804779
 0.23182789632911072
 0.0008737820651969486
 0.9737565182196422
 0.8348631232616956
 0.17022295095760342
 0.37651099884925765

In [63]:
rand(3,5)

3×5 Array{Float64,2}:
 0.217226  0.965544  0.511495   0.844632  0.0431042
 0.82673   0.723941  0.364018   0.815276  0.636314
 0.17729   0.136406  0.0648154  0.341108  0.0882889

In [64]:
randstring()

"7iafsUj8"

In [67]:
randstring('A':'z',50)

"EyeBZsZkZRIOluSSymHIRx_MAPVuXdLpBehzzFeEkSVUJdzRJB"

In [69]:
v1 = Vector(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [70]:
reshape(v1, (2,5))

2×5 Array{Int64,2}:
 1  3  5  7   9
 2  4  6  8  10

# Matrix

In [2]:
zeros(3,5)

3×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [1]:
ones(3,5)

3×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

# tensor

In [3]:

ones(3,5,6)

3×5×6 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 3] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 4] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 5] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

[:, :, 6] =
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [4]:
using Pkg

In [6]:
Pkg.add("LinearAlgebra")

   Updating registry at `C:\Users\bishw\.julia\registries\General`
  Resolving package versions...
Updating `C:\Users\bishw\.julia\environments\v1.5\Project.toml`
  [37e2e46d] + LinearAlgebra
No Changes to `C:\Users\bishw\.julia\environments\v1.5\Manifest.toml`


# Identity matrix

In [8]:
using LinearAlgebra

In [9]:
I(10)

10×10 Diagonal{Bool,Array{Bool,1}}:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1

# How to generate custom matrix

### Now to create a matrix each row elements are seperated by space and each row is identified by a semi colon

In [10]:
M = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [11]:
size(M)

(3, 3)

# Subset rows

In [14]:
M[1,:]

3-element Array{Int64,1}:
 1
 2
 3

# Subset Cols

In [15]:
M[:,2]

3-element Array{Int64,1}:
 2
 5
 8

# Merge two matrix side by side

In [16]:
M

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [17]:
N = [10 11 12; 13 14 15; 16 17 18]

3×3 Array{Int64,2}:
 10  11  12
 13  14  15
 16  17  18

In [18]:
[M N]

3×6 Array{Int64,2}:
 1  2  3  10  11  12
 4  5  6  13  14  15
 7  8  9  16  17  18

In [24]:
hcat(M,N)

3×6 Array{Int64,2}:
 1  2  3  10  11  12
 4  5  6  13  14  15
 7  8  9  16  17  18

# Merge two matrix horizontally

In [20]:
[M;N]

6×3 Array{Int64,2}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12
 13  14  15
 16  17  18

In [26]:
vcat(M,N)

6×3 Array{Int64,2}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12
 13  14  15
 16  17  18

In [27]:
transpose(M)

3×3 Transpose{Int64,Array{Int64,2}}:
 1  4  7
 2  5  8
 3  6  9

# trace of a matrix

In [28]:
tr(M)

15

In [29]:
det(M)

0.0

In [33]:
M = [2 4 5; 1 2 3; 6 7 0]

3×3 Array{Int64,2}:
 2  4  5
 1  2  3
 6  7  0

In [34]:
inv(M)

3×3 Array{Float64,2}:
 -4.2   7.0   0.4
  3.6  -6.0  -0.2
 -1.0   2.0   0.0

In [35]:
UpperTriangular(M)

3×3 UpperTriangular{Int64,Array{Int64,2}}:
 2  4  5
 ⋅  2  3
 ⋅  ⋅  0

In [36]:
LowerTriangular(M)

3×3 LowerTriangular{Int64,Array{Int64,2}}:
 2  ⋅  ⋅
 1  2  ⋅
 6  7  0

In [38]:
eigvecs(M)

3×3 Array{Float64,2}:
 -0.424033  -0.742562  -0.645135
 -0.292089   0.639301  -0.358268
  0.857251  -0.19974   -0.674866

In [39]:
eigvals(M)

3-element Array{Float64,1}:
 -5.352954259951673
 -0.09882411688237432
  9.451778376834048